#!/bin/sh
# initramfs-tools hook: install capsem-init into the initramfs

PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

# Copy our custom init (replaces /init in initramfs)
# chmod 755 is critical -- switch_root will exec this
cp /capsem-init "${DESTDIR}/capsem-init"
chmod 755 "${DESTDIR}/capsem-init"
